spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:testdb # jdbc:h2:file:/data/demo
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.enabled: true

management:
  server:
    port: 9001

    
logging:
  level:
    root: info
    com.example.demo: debug