spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:testdb # jdbc:h2:file:/data/demo
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.enabled: true

jwt:
  header: Authorization
  secret: practice
  token-validity-in-seconds: 86400

management:
  server:
    port: 9001

logging:
  config: classpath:log4j2.yml
